using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Faolline.GraphCore.Editor
{
    /// <summary>
    /// Shared pure core for the identity-constants generators (<c>GraphSignals</c> from
    /// <see cref="SignalConstantsGenerator"/>, <c>GraphVariables</c> from <see cref="VariableConstantsGenerator"/>).
    /// Turns a set of (display name → stable GUID) pairs into a <c>const string</c> class: the SYMBOL is the
    /// PascalCase-sanitized display name (rename-safe: renaming breaks stale code at compile), the VALUE is the
    /// GUID (the runtime key; never changes on rename). Symbol collisions are a blocking error, never a silent
    /// merge. No <c>AssetDatabase</c> here — fully unit-testable.
    /// </summary>
    public static class ConstantsGeneratorCore
    {
        /// <summary>
        /// Builds the C# source for a <c>const string</c> class named <paramref name="className"/> from
        /// (display name, GUID) pairs. Returns <c>false</c> without producing source when two display names
        /// sanitize to the same symbol (blocking collision); <paramref name="errors"/> then lists each collision.
        /// <paramref name="itemNoun"/> is used in the doc comments/errors (e.g. "signal", "parameter") and
        /// <paramref name="menuLabel"/> in the generated file header (e.g. "Signals > Generate Constants").
        /// </summary>
        public static bool TryBuildSource(
            string className, string itemNoun, string menuLabel,
            IReadOnlyList<(string displayName, string guid)> items, out string source, out List<string> errors)
        {
            errors = new List<string>();
            source = null;

            var bySymbol = new Dictionary<string, List<string>>();
            foreach (var (display, _) in items)
            {
                var symbol = Sanitize(display);
                if (!bySymbol.TryGetValue(symbol, out var list)) bySymbol[symbol] = list = new List<string>();
                if (!list.Contains(display)) list.Add(display);
            }
            foreach (var kv in bySymbol)
                if (kv.Value.Count > 1)
                    errors.Add($"Symbol '{kv.Key}' is produced by {kv.Value.Count} distinct {itemNoun}s " +
                               $"(\"{string.Join("\", \"", kv.Value)}\"). Rename one so each has a unique symbol.");
            if (errors.Count > 0) return false;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// Generated by Faolline > {menuLabel}. Do not edit by hand.");
            sb.AppendLine($"// Symbol = {itemNoun} display name (rename-safe: renaming breaks stale code here at compile).");
            sb.AppendLine($"// Value  = {itemNoun} stable GUID (the runtime key; never changes on rename).");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine($"public static class {className}");
            sb.AppendLine("{");
            foreach (var (display, guid) in items.OrderBy(s => Sanitize(s.displayName), System.StringComparer.Ordinal))
            {
                sb.AppendLine($"    /// <summary>{UpperFirst(itemNoun)} \"{XmlEscape(display)}\".</summary>");
                sb.AppendLine($"    public const string {Sanitize(display)} = \"{guid}\";");
            }
            sb.AppendLine("}");
            source = sb.ToString();
            return true;
        }

        /// <summary>
        /// Turns a display name into a valid PascalCase C# identifier: word breaks on any non-alphanumeric run,
        /// each word capitalized; a leading digit is prefixed with <c>_</c>; empty/all-invalid yields <c>_</c>.
        /// </summary>
        public static string Sanitize(string displayName)
        {
            if (string.IsNullOrEmpty(displayName)) return "_";
            var sb = new StringBuilder(displayName.Length);
            bool nextUpper = true;
            foreach (var c in displayName)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true;   // word boundary
                }
            }
            if (sb.Length == 0) return "_";
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string UpperFirst(string s)
            => string.IsNullOrEmpty(s) ? s : char.ToUpperInvariant(s[0]) + s.Substring(1);

        private static string XmlEscape(string s)
            => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
