using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Faolline.GraphCore.Editor
{
    /// <summary>
    /// Generates a <c>GraphSignals</c> static class of <c>const string</c>s from the project's
    /// <see cref="SignalName"/> assets — the compile-checked bridge for raising asset signals from pure host
    /// code. Each constant's SYMBOL is derived from the signal's <see cref="SignalName.DisplayName"/> (legible
    /// in code, e.g. <c>GraphSignals.PlayerInteracted</c>) and its VALUE is the signal's stable GUID
    /// (<see cref="SignalName.Key"/>, the runtime key). Renaming a signal's display name changes only the
    /// symbol (breaking stale code at compile — the intended, safe rename), never the value/GUID (awaits,
    /// raises, and saves keep matching). Menu: <c>Faolline ▸ Signals ▸ Generate Constants</c>.
    /// <para>
    /// The generator ships in graphcore; the generated class lives in the consumer project (each game has its
    /// own signals). It is a plain <c>const string</c> class — zero dependencies.
    /// </para>
    /// </summary>
    public static class SignalConstantsGenerator
    {
        /// <summary>Default output path for the generated class (consumer project).</summary>
        public const string DefaultOutputPath = "Assets/Generated/GraphSignals.cs";

        /// <summary>The generated class name.</summary>
        public const string ClassName = "GraphSignals";

        [MenuItem("Faolline/Signals/Generate Constants")]
        private static void GenerateMenu()
        {
            var signals = new List<(string displayName, string guid)>();
            foreach (var guid in AssetDatabase.FindAssets($"t:{nameof(SignalName)}"))
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var sig = AssetDatabase.LoadAssetAtPath<SignalName>(path);
                if (sig != null && !string.IsNullOrEmpty(sig.Key))
                    signals.Add((sig.DisplayName, sig.Key));
            }

            if (signals.Count == 0)
            {
                Debug.Log("[GraphCore] No SignalName assets found — nothing to generate.");
                return;
            }

            if (!TryBuildSource(signals, out var source, out var errors))
            {
                Debug.LogError("[GraphCore] Signal constant generation aborted (fix the display names and " +
                    "regenerate):\n - " + string.Join("\n - ", errors));
                return;
            }

            var dir = Path.GetDirectoryName(DefaultOutputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(DefaultOutputPath, source);
            AssetDatabase.ImportAsset(DefaultOutputPath);
            Debug.Log($"[GraphCore] Generated {signals.Count} signal constant(s) → {DefaultOutputPath}");
        }

        /// <summary>
        /// Pure, testable core: builds the <c>GraphSignals</c> C# source from (display name, GUID) pairs.
        /// Returns <c>false</c> without producing source when two display names sanitize to the same symbol
        /// (a blocking collision — never a silent merge or auto-suffix); <paramref name="errors"/> then lists
        /// each collision. Otherwise <paramref name="source"/> is the file text.
        /// </summary>
        public static bool TryBuildSource(
            IReadOnlyList<(string displayName, string guid)> signals, out string source, out List<string> errors)
        {
            errors = new List<string>();
            source = null;

            var bySymbol = new Dictionary<string, List<string>>();
            foreach (var (display, _) in signals)
            {
                var symbol = Sanitize(display);
                if (!bySymbol.TryGetValue(symbol, out var list)) bySymbol[symbol] = list = new List<string>();
                if (!list.Contains(display)) list.Add(display);
            }
            foreach (var kv in bySymbol)
                if (kv.Value.Count > 1)
                    errors.Add($"Symbol '{kv.Key}' is produced by {kv.Value.Count} distinct signals " +
                               $"(\"{string.Join("\", \"", kv.Value)}\"). Rename one so each has a unique symbol.");
            if (errors.Count > 0) return false;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// Generated by Faolline > Signals > Generate Constants. Do not edit by hand.");
            sb.AppendLine("// Symbol = signal display name (rename-safe: renaming breaks stale code here at compile).");
            sb.AppendLine("// Value  = signal stable GUID (the runtime key; never changes on rename).");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine($"public static class {ClassName}");
            sb.AppendLine("{");
            foreach (var (display, guid) in signals.OrderBy(s => Sanitize(s.displayName), System.StringComparer.Ordinal))
            {
                sb.AppendLine($"    /// <summary>Signal \"{XmlEscape(display)}\".</summary>");
                sb.AppendLine($"    public const string {Sanitize(display)} = \"{guid}\";");
            }
            sb.AppendLine("}");
            source = sb.ToString();
            return true;
        }

        /// <summary>
        /// Turns a display name into a valid PascalCase C# identifier: word breaks on any non-alphanumeric run,
        /// each word capitalized; a leading digit is prefixed with <c>_</c>; empty/all-invalid yields <c>_</c>.
        /// </summary>
        public static string Sanitize(string displayName)
        {
            if (string.IsNullOrEmpty(displayName)) return "_";
            var sb = new StringBuilder(displayName.Length);
            bool nextUpper = true;
            foreach (var c in displayName)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true;   // word boundary
                }
            }
            if (sb.Length == 0) return "_";
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string XmlEscape(string s)
            => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
